python main.py \
--cfg configs/cifar100.yaml \
--opts FED.IID True \
MISC.SIMILARITY ema_probs \
MODEL.ADAPTATION ours_grad \
FED.BATCH_SIZE 100 \
FED.TEMPORAL_H 0.2 \
FED.SPATIAL_H 0.2 \
MISC.ADAPT_ALL True \
FED.AGG_FREQ 1 \
OPTIM.LR 0.01 \
MISC.RNG_SEED = 2 \
MISC.EMA_PROBS_TEMP = 0.1