python main.py \
--cfg configs/cifar100.yaml \
--opts FED.IID True \
MISC.SIMILARITY weights \
MODEL.ADAPTATION ours \
FED.BATCH_SIZE 10 \
FED.TEMPORAL_H 0.02 \
FED.SPATIAL_H 0.2 \
MISC.ADAPT_ALL True \
FED.AGG_FREQ 1 \
OPTIM.LR 0.001 \
MISC.RNG_SEED  1 \
MISC.EMA_PROBS_TEMP  1.0 \
MISC.TEMP 0.01 \
OPTIM.MT 0.99 \
OPTIM.RST 0.0 \
MISC.USE_IMLOSS  True \
MISC.USE_AUG True \

